version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: LiebeKinder@123
      MYSQL_DATABASE: airflow
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom_airflow:latest
    depends_on:
      - mysql
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor

      # Corrected location for Airflow 2.7+
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+pymysql://root:LiebeKinder%40123@mysql/airflow

      AIRFLOW__CORE__FERNET_KEY: zstNEGIq2EvB4uFm0u_tNyPfz99QUTaiu7lD8famxOE=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      # Gmail Email alerting config
      AIRFLOW__EMAIL__EMAIL_BACKEND: airflow.utils.email.send_email_smtp
      AIRFLOW__SMTP__SMTP_HOST: smtp.gmail.com
      AIRFLOW__SMTP__SMTP_STARTTLS: "True"
      AIRFLOW__SMTP__SMTP_SSL: "False"
      AIRFLOW__SMTP__SMTP_USER: monicjammie@gmail.com
      AIRFLOW__SMTP__SMTP_PASSWORD: kidz hqyi lasn pkat
      AIRFLOW__SMTP__SMTP_PORT: 587
      AIRFLOW__SMTP__SMTP_MAIL_FROM: monicjammie@gmail.com

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email monicjammie@gmail.com --password admin &&
        airflow scheduler & airflow webserver
      "
    restart: always

volumes:
  mysql_data:
